[2024-11-29T22:43:13.554+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-29T22:43:13.595+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1.process_task_tag2 manual__2024-11-29T22:43:05.111285+00:00 [queued]>
[2024-11-29T22:43:13.624+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1.process_task_tag2 manual__2024-11-29T22:43:05.111285+00:00 [queued]>
[2024-11-29T22:43:13.637+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-29T22:43:13.716+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_task_tag2> on 2024-11-29 22:43:05.111285+00:00
[2024-11-29T22:43:13.742+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=391) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-29T22:43:13.745+0000] {standard_task_runner.py:72} INFO - Started process 405 to run task
[2024-11-29T22:43:13.761+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag1', 'process_task_tag2', 'manual__2024-11-29T22:43:05.111285+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag_data.py', '--cfg-path', '/tmp/tmp06wd65wg']
[2024-11-29T22:43:13.781+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask process_task_tag2
[2024-11-29T22:43:14.101+0000] {task_command.py:467} INFO - Running <TaskInstance: dag1.process_task_tag2 manual__2024-11-29T22:43:05.111285+00:00 [running]> on host bffe5982c6e9
[2024-11-29T22:43:14.418+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='dag1' AIRFLOW_CTX_TASK_ID='process_task_tag2' AIRFLOW_CTX_EXECUTION_DATE='2024-11-29T22:43:05.111285+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-29T22:43:05.111285+00:00'
[2024-11-29T22:43:14.422+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-29T22:43:14.499+0000] {dag_data.py:61} ERROR - Une erreur est survenue lors du traitement de sales.csv : KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "bootstrap_servers""}
[2024-11-29T22:43:14.502+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-29T22:43:14.529+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-29T22:43:14.531+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=process_task_tag2, run_id=manual__2024-11-29T22:43:05.111285+00:00, execution_date=20241129T224305, start_date=20241129T224313, end_date=20241129T224314
[2024-11-29T22:43:14.620+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-29T22:43:14.670+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-29T22:43:14.673+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
